### ISSUE TITLE
Status code page, status code: 404, Signing out after posting new or editing title of new post

### ISSUE THREAD

**Issue by PRIMETSS** [madskristensen/Miniblog.Core#14]
Seem to be able to reliably re-create this.
Believe behaviour only shows for **Un-Published Posts**

1. Login
2. Create new test Post (or change title of existing)
3. Un-tick Is Published
4. Save
5. Signout

Browser is redirected to [http://miniblogcore20171027024748.azurewebsites.net/blog/Test/](url)

> Status code page, status code: 404

As its not visible to logged out users, as its un-published.

Looks like a Return-Url issue maybe?

(ps: Nice work!)

**Comment by madskristensen** [comment]
I'm not sure what to do about this one. It seems to me the logic is sound, but it would be nice if you saw a proper 404 message. Perhaps a new issue should be opened instead of this one about a missing custom 404 page

**Comment by PRIMETSS** [comment]
Yeah not sure what people would expect on signing out after editing or creating an 'un-published' post.
But maybe the returnUrl should be set to the root in this case.
Or even should that just be the normal, and make
`<li><a href="~/logout/?returnUrl=/" title="Sign out as administrator">Sign out</a></li>`
always return to the root and remove the setting of a path?

**Comment by madskristensen** [comment]
Yeah, it makes sense that logout always takes you to the home page
