### ISSUE TITLE
404 on Post Comment button click event

### ISSUE THREAD

**Issue by jsmithcio** [madskristensen/Miniblog.Core#2]
1. When trying to add a Comment to a Post, clicking the Post Comment button results in a 404 error.

2. This behavior is also present on the Azure demo site. Screenshot attached.

3. You are a rock star of the coding community. Thank you for your contributions.

![miniblog_core_screenshot](https://user-images.githubusercontent.com/16616631/31306072-0f35d540-aafd-11e7-991d-34ebf08a4e45.jpg)

**Comment by madskristensen** [comment]
Wow, didn't know anyone was looking at this repo just yet!!

Thanks for raising the issue
