### ISSUE TITLE
BlogServiceProviders

### ISSUE THREAD

**Issue by tbasallo** [madskristensen/Miniblog.Core#21]
Are you interested in implementing other providers (in the core project) and taking pull requests, or would you prefer for users to implement as they need on their own and leave outside of this project?

I ask because with the interface created, it would be trivial for others to add other providers (SQL [using things like [NPoco](https://github.com/schotime/NPoco), [dapper](https://github.com/StackExchange/Dapper), ADO.NET, Azure Blob/Table Storage, etc.).

**Comment by madskristensen** [comment]
I was thinking of linking to them all from the README.md or the wiki instead of having them in the project itself. Perhaps if some of them become really popular then it makes sense to move them in

**Comment by tbasallo** [comment]
Makes sense.
