### ISSUE TITLE
No files found matching "/serviceworker.js"

### ISSUE THREAD

**Issue by snmslavk** [madskristensen/Miniblog.Core#27]
Hello,

Maybe I'm doing something wrong but I'm getting this error when I'm trying to run solution.

I see that you registered it here, but I cannot find the file:
```
    // Register service worker
    if ('serviceWorker' in navigator) {
        navigator.serviceWorker.register("/serviceworker.js");
    }
```

Could you guide me where I have to look?

**Comment by madskristensen** [comment]
My bad. Fix on its way. Just delete that for now

**Comment by madskristensen** [comment]
It's been fixed
