### ISSUE TITLE
Live demo site down.

### ISSUE THREAD

**Issue by asadsahi** [madskristensen/Miniblog.Core#38]
@madskristensen sorry this is not to say that something wrong with this project, but is this project setup with some CI or github hook to azure app?

![image](https://user-images.githubusercontent.com/3470892/32888731-2ee0c9da-cac0-11e7-81f0-6bb430baa054.png)

I have been having this issue for quite a while with one of my project as well that one day I managed to deploy site once on azure web app and subsequent deployment ended up in same error and its very hard to debug. I have lost the confidence on auto deployment recently and been doing manual web deploy.

I would say web app deployment isn't as stable as it should be as this issue or similar has already been escalated on other places and most of the time the solutions presented don't work consistently.

[here](https://social.msdn.microsoft.com/Forums/en-US/8f977b50-9d58-48c8-936e-33d11ed478d1/published-aspnet-core-web-api-on-azure-and-it-does-not-work-503-error?forum=AzureAPIApps), [here ](https://stackoverflow.com/questions/45736182/how-to-debug-a-503-error-on-an-azure-web-app), [here](https://stackoverflow.com/questions/44550096/asp-net-core-2-0-on-azure-results-in-a-502-5), [here](https://stackoverflow.com/questions/45787098/asp-net-core-2-web-api-azure-publish-issue), [here](https://stackoverflow.com/questions/29144903/503-errors-service-unavailable-on-azure-websites), [here](url), [here](https://alexandrebrisebois.wordpress.com/2014/06/19/http1-1-503-service-unavailable-lessons-learned-on-azure/), [here](url), [here](https://www.leggetter.co.uk/2009/08/28/windows-azure-503-service-unavailable.html)

Do you have any knowledge on it being down?

**Comment by madskristensen** [comment]
It is now back up. I just restarted the web server (IIS)
