### ISSUE TITLE
How to back up just the Posts / Images

### ISSUE THREAD

**Issue by gabrielmccoll** [madskristensen/Miniblog.Core#53]
Hi there,
Sorry I'm an almost complete nub when it comes to developing but I'm trying to use this excellent project to learn some useful stuff
One thing I'm trying to figure out is what are the files I need to backup to restore my blog 
Is it just the "Posts" folder ? 
Thanks !

**Comment by madskristensen** [comment]
Yes, you just need to backup the "Posts" folder. It contains all the blog posts including images
