### ISSUE TITLE
More security to PWD

### ISSUE THREAD

**Issue by braegelno5** [madskristensen/Miniblog.Core#99]
If we send the PWD to the server it's secure, only on HTTPS transmission, and even if there exist a HTTPS sniffer on the communion channel the PWD will show up in the dump. 
So if we encrypt with rot13 the PWD on the client site, nobody is able to see it easily, expect a keyboard sniffer. It's a minimalistic approach against such vulnerabilities.
The question will be, a PR for this, will be welcome?
To hash the PWD with username on client it's maybe more than  'mini'..

**Comment by dlidstrom** [comment]
What is a PWD? Thanks!

**Comment by braegelno5** [comment]
PWD = password

**Comment by dlidstrom** [comment]
Ah, obvious. Thanks!

**Comment by dlidstrom** [comment]
From [Wikipedia](https://en.wikipedia.org/wiki/ROT13):

“The algorithm provides virtually no cryptographic security”

Doesn’t seem like rot13 would do any good. If someone has cracked https then presumably they can easily “crack” rot13.

**Comment by braegelno5** [comment]
You are right, it's only a paranoid obfuscation for a MiTM (eTLS) scenario;) My suggestion is a rot18.inverse, so a big data analyze sees only strings like other pwd's

**Comment by braegelno5** [comment]
Another point of view, would it be welcome, if we have some code against password brute forcing in account service? For example slow down des Response If repeatly ValidateUser was false for this caller.

**Comment by dlidstrom** [comment]
IMO this is not the responsibility of a blogging library. Especially not a “mini”.
